CREATE TABLE "images" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "user_id" UUID NOT NULL,
  "filename" VARCHAR,
  "url" VARCHAR,
  "created_at" TIMESTAMP DEFAULT Now(),
  "updated_at" TIMESTAMP DEFAULT Now()
);

ALTER TABLE "images" ADD CONSTRAINT "unique_filename" UNIQUE ("filename");
ALTER TABLE "images" ADD CONSTRAINT "fk_images_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id");
